version: '3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'stickynotes'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
  djangoweb:
    image: rajchandvaniya/quantiphi_workshop:v1
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - mysqldb
